//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THPTPhuBinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ChiTietPhieuMuon
    {
        [DisplayName("Mã chi tiết")]
        public int MaCT { get; set; }
        [DisplayName("Mã phiếu mượn")]
        public Nullable<int> MaPM { get; set; }
        [DisplayName("Số lượng")]
        public int SoLuong { get; set; }
        public Nullable<int> MaSach { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
        [DisplayName("Sách")]
        public virtual Sach Sach { get; set; }
    }
}
