//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THPTPhuBinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
        [DisplayName("Mã nhân viên")]
        public string MaNV { get; set; }
        [DisplayName("ID")]
        public Nullable<int> MaNguoi { get; set; }
        [DisplayName("Tên đăng nhập")]
        public string TaiKhoan { get; set; }
    
        public virtual Nguoi Nguoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
