//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THPTPhuBinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>();
        }
        [DisplayName("Mã sách")]
        public int MaSach { get; set; }
        [DisplayName("Tên sách")]
        public string TenSach { get; set; }
        [DisplayName("Tác giả")]
        public string TenTG { get; set; }
        [DisplayName("Số lượng")]
        public int SoLuong { get; set; }
        [DisplayName("Số lượng thực tế")]
        public int SoLuongTT { get; set; }
        [DisplayName("Mã thể loại")]
        public int MaTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Chi tiết phiếu mượn")]
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        [DisplayName("Thể loại")]
        public virtual TheLoai TheLoai { get; set; }
    }
}
